const ARMOR_PART_TYPE = {
  DIAMOND_BOOTS: 'diamond_boots',
  DIAMOND_LEGGINGS: 'diamond_leggigns',
  DIAMOND_CHESTPLATE: 'diamond_chestplate',
  DIAMOND_HELMET: 'diamond_helmet',
  IRON_BOOTS: 'iron_boots',
  IRON_LEGGINGS: 'iron_leggings',
  IRON_CHESTPLATE: 'iron_chestplate',
  IRON_HELMET: 'iron_helmet',
  GOLD_BOOTS: 'gold_boots',
  GOLD_LEGGINGS: 'gold_leggings',
  GOLD_CHESTPLATE: 'gold_chestplate',
  GOLD_HELMET: 'gold_helmet',
  CHAINMAIL_BOOTS: 'chainmail_boots',
  CHAINMAIL_LEGGINGS: 'chainmail_leggings',
  CHAINMAIL_CHESTPLATE: 'chainmail_chestplate',
  CHAINMAIL_HELMET: 'chainmail_helmet',
} as const

const TOOL_TYPE = {
  DIAMOND_PICKAXE: 'diamond_pickaxe',
  DIAMOND_AXE: 'diamond_axe',
  DIAMOND_SHOVEL: 'diamond_shovel',
  DIAMOND_SWORD: 'diamond_sword',
  DIAMOND_: 'diamond_hoe',
  IRON_PICKAXE: 'iron_pickaxe',
  IRON_AXE: 'iron_axe',
  IRON_HOE: 'iron_hoe',
  IRON_SWORD: 'iron_sword',
  IRON_SHOVEL: 'iron_shovel',
  GOLD_PICKAXE: 'gold_pickaxe',
  GOLD_AXE: 'gold_axe',
  GOLD_HOE: 'gold_hoe',
  GOLD_SWORD: 'gold_sword',
  GOLD_SHOVEL: 'gold_shovel',
  WODDEN_PICKAXE: 'wodden_pickaxe',
  FISHING_ROD: 'fishing_rod',
} as const

const OTHERS_ITEMS = {
  BOW: 'bow',
  SHIELD: 'shield',
  SHULKER_BOX: 'shulker_box',
  EMPTY_MAP: 'empty_map',
  ELYTRA: 'elytra',
  SHEARS: 'shears',
  BOOK: 'book',
  BOOK_AND_QUILL: 'book_and_quill',
  ENDER_PEARL: 'ender_pearl',
} as const

const ENCHANT_NAME_TYPE = {
  PROTECTION: 'protection',
  UNBREAKING: 'unbreaking',
  MENDING: 'mending',
  LOOTING: 'looting',
  RESPIRATION: 'respiration',
  FEATHER_FALLING: 'feather_falling',
  DEPTH_STRIDER: 'depth_strider',
  EFFICIENCY: 'efficiency',
  FORTUNE: 'fortune',
  SILK_TOUCH: 'silk_touch',
  POWER: 'power',
  INFINITY: 'infinity',
  PUNCH: 'punch',
  FLAME: 'flame',
  FIRE_ASPECT: 'fire_aspect',
  AQUA_AFFINITY: 'aqua_affinity',
  BANE_OF_ARTHROPODS: 'bane_of_arthropds',
  BLAST_PROTECTION: 'blast_protection',
  FIRE_PROTECTION: 'fire_protection',
  FROST_WALKER: 'frost_walker',
  KNOCKBACK: 'knockback',
  LUCK_OF_THE_SEA: 'luck_of_the_sea',
  LURE: 'lure',
  PROJECTILE_PROTECTION: 'projectile_protection',
  SHARPNESS: 'sharpness',
  SMITE: 'smite',
  THORNS: 'thorns',
  SWEEPING: 'sweeping',
  SWEEPING_EDGE: 'sweeping_edge',
} as const

const MOB_TYPE = {
  ZOMBIFIED_PIGLIN: 'zombified_piglin',
  ZOMBIE_PIGMAN: 'zombie_pigman',
  ZOMBIE: 'zombie',
  ZOMBIE_VILLAGER: 'zombie_villager',
  SKELETON: 'skeleton',
  WITHER_SKELETON: 'wither_skeleton',
  MAGMA: 'magma_cube',
  HORSE: 'horse',
  WOLF: 'wolf',
} as const

const LEVEL_WITH_NUMBER_ROMAN = {
  ONE: 'I',
  TWO: 'II',
  THREE: 'III',
  FOUR: 'IV',
  FIVE: 'V',
} as const

const LEVEL_NUMBER = {
  ONE: '1',
  TWO: '2',
  THREE: '3',
  FOUR: '4',
  FIVE: '5',
} as const

const WEIGHTS = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
} as const

const ARMOR_TYPE = {
  CHAINMAIL: 'chainmail',
  LEATHER: 'leather',
  GOLD: 'gold',
  IRON: 'iron',
  DIAMOND: 'diamond',
  NETHERITE: 'netherite',
} as const

const GAMEMODE_TYPE = {
  CREATIVO: 'Creativo',
  CREATIVE: 'Creative',
  SURVIVAL: 'Survival',
  ESPECTADOR: 'Espectador',
  SPECTATOR: 'Spectator',
  ADVENTURE: 'Adventure',
  AVENTURA: 'Aventura',
} as const

const BIOME_TYPE = {
  TAIGA: 'taiga',
  EXTREME_HILLS: 'extreme hills',
  SWAMP: 'swamp',
  PLAINS: 'plains',
  JUNGLE: 'jungle',
  NETHER: 'nether',
} as const

const ALL_VERSIONS = {
  '1.X': '1.X',
  '1.4': '1.4',
  '1.4.2': '1.4.2',
  '1.4.4': '1.4.4',
  '1.4.5': '1.4.5',
  '1.4.6': '1.4.6',
  '1.4.7': '1.4.7',
  '1.5': '1.5',
  '1.5.1': '1.5.1',
  '1.5.2': '1.5.2',
  '1.6': '1.6',
  '1.6.1': '1.6.1',
  '1.6.2': '1.6.2',
  '1.6.4': '1.6.4',
  '1.7': '1.7',
  '1.7.2': '1.7.2',
  '1.7.4': '1.7.4',
  '1.7.5': '1.7.5',
  '1.7.6': '1.7.6',
  '1,.7.7': '1,.7.7',
  '1.7.8': '1.7.8',
  '1.7.9': '1.7.9',
  '1.7.10': '1.7.10',
  '1.8': '1.8',
  '1.8.1': '1.8.1',
  '1.8.2': '1.8.2',
  '1.8.3': '1.8.3',
  '1.8.4': '1.8.4',
  '1.8.5': '1.8.5',
  '1.8.6': '1.8.6',
  '1.8.7': '1.8.7',
  '1.8.8': '1.8.8',
  '1.8.9': '1.8.9',
  '1.9': '1.9',
  '1.9.1': '1.9.1',
  '1.9.2': '1.9.2',
  '1.9.3': '1.9.3',
  '1.9.4': '1.9.4',
  '1.10': '1.10',
  '1.10.1': '1.10.1',
  '1.10.2': '1.10.2',
  '1.11': '1.11',
  '1.11.1': '1.11.1',
  '1.11.2': '1.11.2',
  '1.12': '1.12',
  '1.12.1': '1.12.1',
  '1.12.2': '1.12.2',
  '1.13': '1.13',
  '1.13.1': '1.13.1',
  '1.13.2': '1.13.2',
  '1.14': '1.14',
  '1.14.1': '1.14.1',
  '1.14.2': '1.14.2',
  '1.14.3': '1.14.3',
  '1.14.4': '1.14.4',
  '1.15': '1.15',
  '1.15.1': '1.15.1',
  '1.15.2': '1.15.2',
  '1.16': '1.16',
  '1.16.1': '1.16.1',
  '1.16.2': '1.16.2',
  '1.16.3': '1.16.3',
  '1.16.4': '1.16.4',
  '1.16.5': '1.16.5',
  '1.17': '1.17',
  '1.17.1': '1.17.1',
  '1.18': '1.18',
  '1.18.1': '1.18.1',
  '1.18.2': '1.18.2',
  '1.19': '1.19',
  '1.19.1': '1.19.1',
  '1.19.2': '1.19.2',
  '1.19.3': '1.19.3',
  '1.19.4': '1.19.4',
  '1.20': '1.20',
  '1.20.1': '1.20.1',
  '1.20.2': '1.20.2',
  '1.20.3': '1.20.3',
  '1.20.4': '1.20.4',
  '1.20.5': '1.20.5',
  '1.20.6': '1.20.6',
  '1.21': '1.21',
  '1.21.1': '1.21.1',
  '1.21.2': '1.21.2',
  '1.21.3': '1.21.3',
  '1.21.4': '1.21.4',
  '1.21.5': '1.21.5',
} as const

const MONTHS_TYPE = {
  ENERO: 'Enero',
  FEBRERO: 'Febrero',
  MARZO: 'Marzo',
  ABRIL: 'Abril',
  MAYO: 'Mayo',
  JUNIO: 'Junio',
  JULIO: 'Julio',
  AGOSTO: 'Agosto',
  SEPTIEMBRE: 'Septiembre',
  OCTUBRE: 'Octubre',
  NOVIEMBRE: 'Noviembre',
  DICIEMBRE: 'Diciembre',
} as const

const YEARS_CUSTOM_TYPE = {
  '19': '19',
  '20': '20',
  '21': '21',
  '22': '22',
  '23': '23',
  '24': '24',
  '25': '25',
  'Oct-17/Jun-19': 'Oct-17/Jun-19',
} as const

const SCHEMAS_KEY = {
  SURVI_API_SCHEMA: 'SurviAPISchema',
  SURVI_API_EPISODE_SCHEMA: 'SurviAPIEpisodeSchema',
  SURVI_API_CALC_SCHEMA: 'SurviAPICALCSchema',
  SURVI_API_EPISODES_EXTENDED_SCHEMA: 'SurviAPIEpisodesExtendedSchema',
  SURVI_API_EPISODES_SCHEMA: 'SurviAPIEpisodesSchema',
  SURVI_API_EXTRAS_SCHEMA: 'SurviAPIExtrasSchema',
  SURVI_API_IMAGES_AND_INFO_SCHEMA: 'SurviAPIImagesAndInfoSchema',
  SURVI_API_PETS_SCHEMA: 'SurviAPIPetsSchema',
  SURVI_API_PROJECTS_SCHEMA: 'SurviAPIProjectsSchema',
  SURVI_API_SVGS_SCHEMA: 'SurviAPISVGSSchema',
} as const

export {
  ALL_VERSIONS,
  ARMOR_PART_TYPE,
  ARMOR_TYPE,
  BIOME_TYPE,
  ENCHANT_NAME_TYPE,
  GAMEMODE_TYPE,
  LEVEL_NUMBER,
  LEVEL_WITH_NUMBER_ROMAN,
  MOB_TYPE,
  MONTHS_TYPE,
  OTHERS_ITEMS,
  SCHEMAS_KEY,
  TOOL_TYPE,
  WEIGHTS,
  YEARS_CUSTOM_TYPE,
}

export default {
  ARMOR_PART_TYPE,
  ARMOR_TYPE,
  BIOME_TYPE,
  ENCHANT_NAME_TYPE,
  GAMEMODE_TYPE,
  LEVEL_NUMBER,
  LEVEL_WITH_NUMBER_ROMAN,
  MOB_TYPE,
  OTHERS_ITEMS,
  TOOL_TYPE,
  WEIGHTS,
  SCHEMAS_KEY,
  ALL_VERSIONS,
  YEARS_CUSTOM_TYPE,
  MONTHS_TYPE,
}
